### PR TITLE
Use composeManyExtensions instead of custom foldExtensions implementation

### PR DESCRIPTION
**Pull request by balsoft**
Added in <https://github.com/nixos/nixpkgs/commit/c3b35f21f78a3d23aaf40b70fe8865598ddc6729>

### CODE REVIEW

**Review by zhenyavinogradov — COMMENTED** [review]
What do you think about removing `foldExtensions` from here and replacing it with `composeExtensions` from nixpkgs in places where we use it? It would help with keeping serokell.nix smaller.

**Comment by balsoft** [comment]
Go ahead!

**Comment by zhenyavinogradov** [comment]
Ok, I'll do it

**Comment by zhenyavinogradov** [comment]
https://github.com/serokell/serokell.nix/pull/45

**Pull request closed without merging**
